#!/bin/bash
# Generate BuildInfo.swift into the build dir so the app can show WHICH build is
# running (Settings › Advanced › Diagnostics). The file is generated on every
# build — never checked in — and appended to the swiftc source list by build.sh
# and build-dmg.sh (it lives outside the OpenWhisp/ glob on purpose).
#
# Usage (source, don't exec):
#   source "$PROJECT_DIR/scripts/generate-build-info.sh"
#   generate_build_info "$BUILD_DIR"    # writes + echoes the .swift file path

generate_build_info() {
    local out_dir="$1"
    local out="$out_dir/BuildInfo.swift"
    mkdir -p "$out_dir"

    local commit branch date dirty
    commit="$(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    branch="$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo unknown)"
    date="$(date "+%Y-%m-%d %H:%M")"
    if [ -n "$(git -C "$PROJECT_DIR" status --porcelain 2>/dev/null)" ]; then
        dirty="true"
    else
        dirty="false"
    fi

    cat > "$out" <<SWIFT
// Generated by scripts/generate-build-info.sh — DO NOT EDIT, not checked in.
// Identifies the running build (Settings › Advanced › Diagnostics).
enum BuildInfo {
    static let commit = "$commit"
    static let branch = "$branch"
    static let date = "$date"
    static let dirty = $dirty

    /// e.g. "abc1234 (main, 2026-07-11 09:12)" — "+" marks uncommitted changes.
    static var display: String {
        "\(commit)\(dirty ? "+" : "") (\(branch), \(date))"
    }
}
SWIFT
    echo "$out"
}
